
server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:h2:file:./data/quickdrop
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

file:
  upload-dir: ./uploads